#!/bin/sh /etc/rc.common

NAME="cms"
USE_PROCD=1
START=76

STOP=8

APP_PATH="/root/secret/cms.arm"       
APP_ARGS=""                     
LOG_FILE="/var/log/${NAME}.log"
RESPAWN_DELAY=2
RESPAWN_MAX=0


start_service() {
    mkdir -p $(dirname "$LOG_FILE")

    procd_open_instance

    procd_set_param command "$APP_PATH" $APP_ARGS

    procd_set_param stdout "$LOG_FILE"
    procd_set_param stderr "$LOG_FILE"

    procd_set_param respawn "$RESPAWN_DELAY" "$RESPAWN_MAX"

    procd_close_instance

}

stop_service() {
    echo "Stopping ${NAME}..."
}

restart() {
    stop
    start
}

status() {
    procd_status
}