#!/bin/sh /etc/rc.common

NAME="diskdec"
USE_PROCD=1
START=70

STOP=10

APP_PATH="/etc/diskdec"       
APP_ARGS="daemon"                     
RESPAWN_DELAY=2
RESPAWN_MAX=0


start_service() {
    procd_open_instance

    procd_set_param command "$APP_PATH" $APP_ARGS

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_set_param respawn "$RESPAWN_DELAY" "$RESPAWN_MAX"

    procd_close_instance
    echo "Stating ${NAME}..."
}

stop_service() {
    echo "Stopping ${NAME}..."
}

restart() {
    stop
    start
}

status() {
    procd_status
}
