#!/bin/sh /etc/rc.common

NAME="proxymanager"
USE_PROCD=1
START=77

STOP=7

APP_PATH="/root/secret/proxymanager-arm"       
APP_ARGS="-c /root/secret/network_config.json"                     
RESPAWN_DELAY=2
RESPAWN_MAX=0


start_service() {
    procd_open_instance

    procd_set_param command "$APP_PATH" $APP_ARGS

    procd_set_param stdout 1
    procd_set_param stderr 1

    procd_set_param respawn "$RESPAWN_DELAY" "$RESPAWN_MAX"

    procd_close_instance
    echo "Stating ${NAME}..."
}

stop_service() {
    echo "Stopping ${NAME}..."
}

restart() {
    stop
    start
}

status() {
    procd_status
}
